// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9R-zdSmi5HIVb-405ZIvgiPXj5B2YrBE',
    appId: '1:424755843152:web:ee6afa5a43761c92a68155',
    messagingSenderId: '424755843152',
    projectId: 'rentify-bda6d',
    authDomain: 'rentify-bda6d.firebaseapp.com',
    storageBucket: 'rentify-bda6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA9FStEhclV3p4lIWZ-17pJep-DRd01eM',
    appId: '1:424755843152:android:09adb02c20cec021a68155',
    messagingSenderId: '424755843152',
    projectId: 'rentify-bda6d',
    storageBucket: 'rentify-bda6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0MsBE8fGFWuTe3XSbRdrieC7v0TnnaVQ',
    appId: '1:424755843152:ios:e46569f38057fdf7a68155',
    messagingSenderId: '424755843152',
    projectId: 'rentify-bda6d',
    storageBucket: 'rentify-bda6d.firebasestorage.app',
    iosBundleId: 'com.example.rentify',
  );
}
